#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

/**
 * Start the console application.
 */
$app = new Application('Dandy', 'beta');

$app->add(new \Dandy\Book\BuildCommand());

$app->run();
