#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

/**
 * Start the console application.
 */
$app = new Application('Dendy', 'beta');


$app->add(new \Dendy\Book\BuildCommand());

$app->run();
